#!/bin/sh
# bump15
if [ ! -e .extracted/complete ] || [ streamer.tgz -nt .extracted/complete ]; then
    rm -rf .extracted
    mkdir -p .extracted
    tar xfvz streamer.tgz -C .extracted
    touch .extracted/complete
fi
export LD_LIBRARY_PATH=$PWD/.extracted
exec python3 ./streamlink_wrap.py
